import type { Metadata } from "next";
import "./globals.css";
import { FloatingNavJSX } from "@/components/custom/Nav";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import { SocketProvider } from "@/socket/socket";

export const metadata: Metadata = {
  title: "swiftDeploye",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#1C1C1C] w-screen">
        <SocketProvider>
          <Toaster />
          <NextTopLoader color="#fff" />
          <FloatingNavJSX />
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
