import type { Metadata } from "next";
import "./globals.css";
import { FloatingNavJSX } from "@/components/custom/Nav";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "swiftDeploye",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#1C1C1C] w-screen">
        <NextTopLoader color="#fff" />
        <FloatingNavJSX />
        {children}
      </body>
    </html>
  );
}
